---
title: "R x PostgreSQL using RPostgres"
output: html_document
date: "2023-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connect Database

```{r}
library(RPostgres)
library(DBI)
source("conf.R")

con <- DBlocal
```

## Select Query

## Country with Most Death

```{r}
country_most_death <- dbGetQuery(con, 
                     "SELECT c.country_name, SUM(d.deaths) death_total 
                     FROM country c, data d, time t
                     WHERE c.country_id = d.country_id 
                     AND t.time_id = d.time_id 
                     GROUP BY c.country_name
                     ORDER BY death_total DESC")
```

```{r}
country_most_death
```

### Countries death ratio

```{r}
country_death_ratio <- dbGetQuery(con, 
                     "SELECT c.country_name, SUM(d.deaths) death_total, c.population 
						          -- , (SUM(d.deaths)/c.population) as ratio
                        FROM country c, data d, time t
                        WHERE c.country_id = d.country_id
                        AND t.time_id = d.time_id
						            GROUP BY c.country_name, c.population
					  	          ORDER BY death_total DESC;")
```

```{r}
country_death_ratio
```

```{r}
country_death_ratio['ratio'] <- round(country_death_ratio['death_total']/country_death_ratio['population'], 3)
country_death_ratio
```

### Tab COVID-19 by Country

```{r}
q1 <- "
      SELECT b.date as Date
            , a.continent as Continent  
            , a.convert_name as Country
            , b.cases as Covid_Case
            , b.deaths as Cases_of_Covid_Death
            , b.recovered as Covid_Recovery_Cases
            --, c.source_name as Source
      FROM country a
      JOIN (SELECT ad.time_id
      	    , it.date
      	    , ad.country_id
      	    , ad.cases
      	    , ad.deaths
      	    , ad.recovered
      	    --, ad.source_id
            FROM data ad
            JOIN time it ON it.time_id=ad.time_id
            GROUP BY ad.time_id
            		, it.date
      		, ad.country_id
      		, ad.cases
      	 	, ad.deaths
      	 	, ad.recovered
      		, ad.source_id
      	 ) b ON b.country_id = a.country_id
      --JOIN source c ON c.source_id=b.source_id
      GROUP BY b.date
      	, a.continent
      	, a.convert_name
      	, b.cases
      	, b.deaths
      	, b.recovered
      --, c.source_name
      ORDER BY b.date asc
      "
```

```{r}
g1 <- dbGetQuery(con, q1)
g1
```

## Tab list of countries affected by covid and carrying out covid testing

```{r}
q2 <- "
      SELECT c.date as Date
      	, d.convert_name as Country
      	, a.value as Number_of_Test
      	, sum(b.cases) as Covid_Case
      	, sum(b.deaths) as Cases_of_Covid_Death
      	, sum(b.recovered) as Covid_Recovery_Cases
      FROM country_testing_policy a
      JOIN (SELECT time_id
      	    , country_id
      	    , cases
      	    , deaths
      	    , recovered
      FROM data
      GROUP BY time_id
            , country_id
      	  	, cases
      	 	, deaths
      	  	, recovered
      	order by country_id asc) b ON b.time_id=a.time_id AND b.country_id=a.country_id
      JOIN time c ON c.time_id = a.time_id
      JOIN country d ON d.country_id = a.country_id
      GROUP BY c.date
      	, d.convert_name
      	, a.value
      HAVING sum(b.cases) > 0
      "
```

```{r}
g2 <- dbGetQuery(con, q2)
g2
```

## Health Index By Country and Mitigation

```{r}
q3 <- "
      SELECT c.date as Date_Based_On_Health_Index
            , d.convert_name as Country
            , a.value as Health_Index
            , b.measure_value as Countermeasures_Mitigation
      FROM country_health_index a
      JOIN measurement b on b.country_id=a.country_id
      JOIN time c ON c.time_id=a.time_id 
      JOIN country d ON d.country_id=a.country_id
      "
```

```{r}
g3 <- dbGetQuery(con, q3)
g3
```

